output: circle_output
log_freq: 100 
image_writer_freq: 100 

data:
  batch_size: 512
  num_workers: 16
  image_folder: /file/tian/data/glint360k
  megaface_data_root: /file/tian/data/megaface_clean
  megaface_face_folders: faces,facescrub_images,megaface_images

model:
  backbone:
    network: vit_s
    input_size: [112, 112]
    patch_size: 8
    freeze_patch_embed: True
    num_features: 512 
    ckpt: False
  gamma: 256 
  m: 0.25 
  ckpt: False

train:
  epochs: 100
  save_epochs: 10
  warmup_epochs: 10
  lr: 1.e-3
  lr_end: 1.e-8
  weight_decay: 1.e-4
